# Generated by Django 5.0.7 on 2024-08-04 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('place_name', models.CharField(max_length=50)),
                ('place_address', models.CharField(max_length=100)),
                ('place_like', models.IntegerField()),
                ('place_latitude', models.FloatField()),
                ('place_longitude', models.FloatField()),
                ('subCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('startpoint_name', models.CharField(max_length=50)),
                ('startpoint_address', models.CharField(max_length=50)),
                ('startpoint_x', models.IntegerField()),
                ('startpoint_y', models.IntegerField()),
                ('endpoint_name', models.CharField(max_length=50)),
                ('endpoint_address', models.CharField(max_length=50)),
                ('endpoint_x', models.IntegerField()),
                ('endpoint_y', models.IntegerField()),
                ('date', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Route_places',
            fields=[
                ('route_places_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_like', models.BooleanField()),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='route.place')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.route')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='places',
            field=models.ManyToManyField(related_name='routes', through='route.Route_places', to='route.place'),
        ),
    ]
