# Generated by Django 5.0.7 on 2024-08-04 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('startpoint_name', models.CharField(max_length=50)),
                ('startpoint_address', models.CharField(max_length=50)),
                ('startpoint_x', models.IntegerField()),
                ('startpoint_y', models.IntegerField()),
                ('endpoint_name', models.CharField(max_length=50)),
                ('endpoint_address', models.CharField(max_length=50)),
                ('endpoint_x', models.IntegerField()),
                ('endpoint_y', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Route_places',
            fields=[
                ('route_places_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_like', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('place_name', models.CharField(max_length=50)),
                ('place_address', models.CharField(max_length=100)),
                ('place_like', models.IntegerField()),
                ('place_latitude', models.FloatField()),
                ('place_longitude', models.FloatField()),
                ('subCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.subcategory')),
            ],
        ),
    ]
