# Generated by Django 5.0.7 on 2024-08-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_address',
            field=models.CharField(max_length=100),
        ),
    ]
