# Generated by Django 5.0.7 on 2024-08-02 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_alter_place_place_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='subcategory_id',
            new_name='subCategory',
        ),
    ]
