# Generated by Django 5.0.7 on 2024-08-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('route', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20, unique=True)),
                ('route', models.ManyToManyField(related_name='route', to='route.route')),
            ],
        ),
    ]
