# Generated by Django 5.0.7 on 2024-08-05 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hashtag', '0001_initial'),
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route_hashtag',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.route'),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='route',
            field=models.ManyToManyField(related_name='hashtag', through='hashtag.Route_Hashtag', to='route.route'),
        ),
    ]
