# Generated by Django 5.0.7 on 2024-08-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0001_initial'),
        ('route', '0004_rename_subcategory_id_place_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='route',
            field=models.ManyToManyField(related_name='route', to='route.route'),
        ),
    ]
